import { Inter } from "next/font/google";
import "./globals.css";
import NavComponents from "./components/NavComponents";
import FooterComponents from "./components/FooterComponents";
import HomePageComponents from "./components/HomePageComponents";
import MovieDetailsComponents from "./view-movie-details/[movieId]/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundColor:"#612114"}} className={inter.className}>
      <NavComponents/>
        {children}
    
      </body> 
    </html>
  );
}
